version: '3.7'

services:
  nginx:
    build: 
      context: .
      dockerfile: "Dockerfile.nginx"
    container_name: auth_github_nginx
    ports:
      - 80:80
      - 443:443
    links:
      - auth_github
      
      

  auth_github:
    build:
      context: .
    container_name: auth_github_app
    env_file:
      - .env-non-dev
    command: ["gunicorn", "app.main:app", "--workers", "1", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind=0.0.0.0:8000" ]
    #ports:
      #- 7777:8000

 

 








    


    

